# Generated by Django 3.1 on 2020-11-27 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='access_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 0, 35, 56, 33740), verbose_name='access_start'),
        ),
        migrations.AlterField(
            model_name='key',
            name='access_stop',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 0, 35, 56, 33740), verbose_name='access_stop'),
        ),
    ]
