# Generated by Django 3.1 on 2020-11-27 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201127_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='access_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 8, 15, 10, 808313), verbose_name='access_start'),
        ),
        migrations.AlterField(
            model_name='key',
            name='access_stop',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 8, 15, 10, 808313), verbose_name='access_stop'),
        ),
    ]
